# Frontend ConfigMap for Task Management System
# Provides environment configuration for React frontend containers
# Version: 1.0.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: production
  labels:
    app: frontend
    tier: web
    environment: production
    version: "1.0.0"
    component: "task-management-system"
data:
  # API Configuration
  VITE_API_BASE_URL: "https://api.taskmanager.com"
  VITE_API_VERSION: "v1"
  VITE_API_TIMEOUT: "30000"

  # WebSocket Configuration for real-time updates
  VITE_WS_URL: "wss://api.taskmanager.com"

  # Application Configuration
  VITE_APP_NAME: "Task Management System"
  VITE_APP_VERSION: "1.0.0"
  NODE_ENV: "production"

  # Feature Configuration
  VITE_ENABLE_LOGS: "false"
  VITE_MAX_UPLOAD_SIZE: "5242880" # 5MB in bytes

  # Internationalization
  VITE_SUPPORTED_LOCALES: "en,es,fr,de,ja"
  VITE_DEFAULT_LOCALE: "en"

  # Performance Configuration
  VITE_CACHE_DURATION: "300"
  VITE_MAX_RETRIES: "3"
  VITE_PAGE_SIZE: "20"

  # UI Configuration
  VITE_DEFAULT_THEME: "light"
  VITE_REACT_STRICT: "true"

  # Security Configuration
  VITE_ENABLE_MOCK_API: "false"
  VITE_CONTENT_SECURITY_POLICY: "default-src 'self'; connect-src 'self' https://api.taskmanager.com wss://api.taskmanager.com; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; script-src 'self';"
  VITE_SECURE_COOKIE: "true"
  VITE_CORS_ENABLED: "true"

  # Rate Limiting
  VITE_RATE_LIMIT_REQUESTS: "1000"
  VITE_RATE_LIMIT_INTERVAL: "3600"

  # Error Reporting
  VITE_ERROR_REPORTING_ENABLED: "true"
  VITE_ERROR_REPORTING_SAMPLE_RATE: "0.1"

  # Monitoring and Analytics
  VITE_METRICS_ENABLED: "true"
  VITE_PERFORMANCE_MONITORING_ENABLED: "true"
  VITE_USER_TRACKING_ENABLED: "false"

  # Cache Configuration
  VITE_CACHE_STRATEGY: "network-first"
  VITE_CACHE_MAX_AGE: "3600"
  VITE_CACHE_STALE_WHILE_REVALIDATE: "true"

  # API Request Configuration
  VITE_REQUEST_TIMEOUT: "30000"
  VITE_REQUEST_RETRIES: "3"
  VITE_REQUEST_BACKOFF: "exponential"
  VITE_REQUEST_COMPRESSION: "true"

  # WebSocket Configuration
  VITE_WS_RECONNECT_ATTEMPTS: "5"
  VITE_WS_RECONNECT_INTERVAL: "1000"
  VITE_WS_HEARTBEAT_INTERVAL: "30000"