# Kubernetes Secret resource for storing sensitive backend configuration
# Version: 1.0.0
# Enhanced security with AES-256-GCM encryption and auto-rotation
apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: production
  labels:
    app: task-management
    component: backend
    environment: production
    managed-by: terraform
  annotations:
    encryption.kubernetes.io/mode: "aes-256-gcm"
    secret.kubernetes.io/auto-rotation: "enabled"
    secret.kubernetes.io/rotation-period: "30d"
type: Opaque
stringData:
  # Database credentials and SSL configuration
  database.username: "${DATABASE_USERNAME}"
  database.password: "${DATABASE_PASSWORD}"
  database.host: "${DATABASE_HOST}"
  database.port: "${DATABASE_PORT}"
  database.name: "${DATABASE_NAME}"
  database.ssl_mode: "verify-full"
  database.ssl_cert: |
    ${DATABASE_SSL_CERT}
  database.ssl_key: |
    ${DATABASE_SSL_KEY}
  database.ssl_root_cert: |
    ${DATABASE_SSL_ROOT_CERT}

  # Redis configuration with TLS
  redis.password: "${REDIS_PASSWORD}"
  redis.host: "${REDIS_HOST}"
  redis.port: "${REDIS_PORT}"
  redis.tls_enabled: "true"
  redis.tls_cert: |
    ${REDIS_TLS_CERT}
  redis.tls_key: |
    ${REDIS_TLS_KEY}
  redis.tls_ca_cert: |
    ${REDIS_TLS_CA_CERT}

  # JWT authentication configuration
  jwt.access_token_secret: "${JWT_ACCESS_TOKEN_SECRET}"
  jwt.refresh_token_secret: "${JWT_REFRESH_TOKEN_SECRET}"
  jwt.token_issuer: "task-management-system"
  jwt.token_audience: "task-management-api"
  jwt.access_token_expiry: "1h"
  jwt.refresh_token_expiry: "7d"

  # External service credentials
  external.sendgrid_api_key: "${SENDGRID_API_KEY}"
  external.sendgrid_sender_email: "${SENDGRID_SENDER_EMAIL}"
  external.auth0_domain: "${AUTH0_DOMAIN}"
  external.auth0_client_id: "${AUTH0_CLIENT_ID}"
  external.auth0_client_secret: "${AUTH0_CLIENT_SECRET}"
  external.aws_access_key: "${AWS_ACCESS_KEY}"
  external.aws_secret_key: "${AWS_SECRET_KEY}"
  external.aws_region: "${AWS_REGION}"
  external.aws_s3_bucket: "${AWS_S3_BUCKET}"